```{r}
library(rjson)
library(tidyverse)
result1 <- fromJSON(file = "Country_density.json")
density_df1 <- data.frame(result1$`Alpha-3 code`)
density_df2 <- data.frame(result1$`Area Global`)
density_df3 <- data.frame(result1$`Share of Active Ports`)
density_df4 <- data.frame(result1$Gini)
density_df5 <- data.frame(result1$`Overall Vessels In Country`)
density_df6 <- data.frame(result1$`Overall Ports`)
density <- c(density_df1,density_df2,density_df3,density_df4,density_df5,density_df6)
density_t <- lapply(density,t)
density_t_df <- lapply(density_t, data.frame)
df1 <- data.frame(t(density_df1))
df1['Area_Global'] <- t(density_df2)
df1["Share of Active "] <- t(density_df3)
df1["Gini"] <- t(density_df4)
df1["Overall_Vessels_In_Port"] <- t(density_df5)
df1["Overall_Ports "] <- t(density_df6)
df1
```

```{r}
df2 <- df1 %>% select(Area_Global, Overall_Vessels_In_Port) %>% group_by(Area_Global) %>%
summarise(ports_total = sum(Overall_Vessels_In_Port))
install.packages("ggcharts")
library(ggplot2)
library(ggcharts)
```

```{r}
ggcharts_set_theme("theme_nightblue")
bar_chart(data = df2, x = Area_Global, y = ports_total, top_n = 10) +
labs(
x = 'Area',
y = "Number of ports",
title = "Overall global area statistics"
)
```

